/* Generated by pecans-spec. Do not edit. */
import { Module } from "../module";
import { ForumSearchResponse, TCResponse, ViewPostsResponse } from "../generated/types";

export class ForumModule extends Module {
    public async viewPosts(threadId: number, fetchType: string, postId: number = 0, reverse: boolean = false, includePost: boolean = true): Promise<ViewPostsResponse> {
        return await this.client._call<ViewPostsResponse>(
            "forum.viewposts",
            {
                "threadId": threadId,
                "type": fetchType,
                "postId": postId,
                "getSomeBackscroll": reverse,
                "includePost": includePost,
                "includeThreadMetadata": true,
            },
        );
    }

    public async replyThread(text: string, threadId: number): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "forum.replythread",
            {
                "text": text,
                "threadId": threadId,
            },
        );
    }

    public async readThread(postId: number, threadId: number): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "forum.readthread",
            {
                "postId": postId,
                "threadId": threadId,
            },
        );
    }

    public async editPost(postId: number, text: string): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "forum.editpost",
            {
                "postId": postId,
                "text": text,
            },
        );
    }

    public async search(query: string): Promise<ForumSearchResponse> {
        return await this.client._call<ForumSearchResponse>(
            "forum.search",
            {
                "query": query,
            },
        );
    }
}
