/* Generated by pecans-spec. Do not edit. */
import { Module } from "../module";
import { AnswerQueueQuestionResponse, AnswerReplyResponse, QuestionFetchResponse, TCResponse } from "../generated/types";
import { DismissAction } from "../enums";

export class AnswerModule extends Module {
    public async fetchNext(): Promise<QuestionFetchResponse> {
        return await this.client._call<QuestionFetchResponse>(
            "answer.getnext",
            {},
        );
    }

    public async dismissQuestion(questionId: number, action: DismissAction): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "answer.dismissquestion",
            {
                "questionId": questionId,
                "action": action,
            },
        );
    }

    public async pollVote(questionId: number, optionNum: number): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "answer.pollvote",
            {
                "questionId": questionId,
                "optionNum": optionNum,
            },
        );
    }

    public async queueQuestion(questionId: number): Promise<AnswerQueueQuestionResponse> {
        return await this.client._call<AnswerQueueQuestionResponse>(
            "answer.queuequestion",
            {
                "questionId": questionId,
            },
        );
    }

    public async reply(questionId: number, text: string): Promise<AnswerReplyResponse> {
        return await this.client._call<AnswerReplyResponse>(
            "answer.reply",
            {
                "questionId": questionId,
                "text": text,
            },
        );
    }
}
