/* Generated by pecans-spec. Do not edit. */
import { Module } from "../module";
import { TCResponse } from "../generated/types";

export class AccountModule extends Module {
    public async register(email: string, username: string, password: string): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "account.register",
            {
                "email": email,
                "username": username,
                "password1": password,
                "password2": password,
                "age": true,
                "tos": true,
            },
        );
    }

    public async activate(token: string): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "account.activate",
            {
                "token": token,
            },
        );
    }
}
