/* Generated by pecans-spec. Do not edit. */
import { Module } from "../module";
import { FolderListResponse, FolderViewResponse, MessageViewResponse, TCResponse } from "../generated/types";

export class MessagesModule extends Module {
    public async folderView(folder: string = "inbox", page: number = 1): Promise<FolderViewResponse> {
        return await this.client._call<FolderViewResponse>(
            "messages.folderview",
            {
                "folder": folder,
                "page": page,
            },
        );
    }

    public async view(conversationId: string, includeHeader: boolean = true, markAsRead: boolean = true, page: number = 1): Promise<MessageViewResponse> {
        return await this.client._call<MessageViewResponse>(
            "messages.view",
            {
                "conversationId": conversationId,
                "includeHeader": includeHeader,
                "markAsRead": markAsRead,
                "page": page,
            },
        );
    }

    public async reply(conversationId: string, text: string, unanonymize: boolean = false): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "messages.reply",
            {
                "conversationId": conversationId,
                "text": text,
                "unanonymize": unanonymize,
            },
        );
    }

    public async folderList(): Promise<FolderListResponse> {
        return await this.client._call<FolderListResponse>(
            "messages.folderlist",
            {},
        );
    }
}
