/* Generated by pecans-spec. Do not edit. */
import { MethodCall, TCJSONResponse } from "./types";
import { TCProfile } from "./generated/types";
import { AccountModule } from "./account";
import { AnswerModule } from "./answer";
import { AuthModule } from "./auth";
import { DrawingModule } from "./drawing";
import { ForumModule } from "./forum";
import { MessagesModule } from "./messages";
import { NotifyModule } from "./notify";

export class ResponseParseError {
    public readonly name: string = "ResponseParseError";
    public readonly message: string = "Failed to parse API response as JSON";
    public readonly responseText: string;
    public readonly cause?: unknown;

    public constructor(responseText: string, cause?: unknown) {
        this.responseText = responseText;
        if (cause !== undefined) {
            this.cause = cause;
        }
    }
}

interface QueuedCall {
    methodCall: MethodCall;
    resolve: (value: unknown) => void;
    reject: (reason: unknown) => void;
}

export class Client {
    static readonly BASE_URI = "https://api.twocansandstring.com/api";
    static readonly VERSION = "1.68";

    #account: AccountModule;
    #answer: AnswerModule;
    #auth: AuthModule;
    #drawing: DrawingModule;
    #forum: ForumModule;
    #messages: MessagesModule;
    #notify: NotifyModule;

    #activeBatch: QueuedCall[] | null = null;

    public profileCache: { [key: string]: TCProfile } = {};

    public authToken?: string;

    public agent: string = "pecans";

    public shouldTrimErrors: boolean = true;

    public get account(): AccountModule {
        return this.#account;
    }

    public get answer(): AnswerModule {
        return this.#answer;
    }

    public get auth(): AuthModule {
        return this.#auth;
    }

    public get drawing(): DrawingModule {
        return this.#drawing;
    }

    public get forum(): ForumModule {
        return this.#forum;
    }

    public get messages(): MessagesModule {
        return this.#messages;
    }

    public get notify(): NotifyModule {
        return this.#notify;
    }

    public get isBatching(): boolean {
        return this.#activeBatch !== null;
    }

    public constructor(auth?: string) {
        this.authToken = auth;
        this.#account = new AccountModule(this);
        this.#answer = new AnswerModule(this);
        this.#auth = new AuthModule(this);
        this.#drawing = new DrawingModule(this);
        this.#forum = new ForumModule(this);
        this.#messages = new MessagesModule(this);
        this.#notify = new NotifyModule(this);
    }

    /** @internal */
    public _call<T>(methodName: string, args: { [key: string]: any }): Promise<T> {
        const methodCall: MethodCall = { fn: methodName, payload: args };

        if (this.#activeBatch !== null) {
            const batch = this.#activeBatch;
            return new Promise<T>((resolve, reject) => {
                batch.push({ methodCall, resolve: resolve as (value: unknown) => void, reject });
            });
        }

        return this.#send([methodCall]).then((res) => this.#build<T>(res, 0));
    }

    public beginBatch(): void {
        this.#activeBatch ??= [];
    }

    public async endBatch(): Promise<void> {
        const batch = this.#activeBatch;
        this.#activeBatch = null;

        if (batch === null || batch.length === 0) {
            return;
        }

        try {
            const res = await this.#send(batch.map((call) => call.methodCall));
            batch.forEach((call, index) => call.resolve(this.#build(res, index)));
        } catch (reason) {
            batch.forEach((call) => call.reject(reason));
        }
    }

    #build<T>(res: TCJSONResponse | undefined, index: number): T {
        res?.profiles?.forEach((profile) => {
            this.profileCache[profile.id] = profile;
        });

        return {
            ok: res?.ok ?? false,
            ...(res?.responses?.[index] ?? {}),
            profiles: res?.profiles,
        } as T;
    }

    async #send(requests: MethodCall[]): Promise<TCJSONResponse | undefined> {
        const headers: { [key: string]: string } = {
            "Content-Type": "application/json",
            "User-Agent": this.agent,
        };

        if (this.authToken != undefined) {
            headers["Cookie"] = "twocansandstring_com_auth2=" + this.authToken;
        }

        const res = await fetch(Client.BASE_URI, {
            method: "POST",
            headers,
            body: JSON.stringify({ auth: this.authToken, requests }),
        });

        if (!res.ok) {
            return Promise.reject();
        }

        if (this.shouldTrimErrors) {
            let text = await res.text();
            text = text.replace(/^(?:.*\n)*{/, "{");
            try {
                return JSON.parse(text) as TCJSONResponse;
            } catch (cause) {
                throw new ResponseParseError(text, cause);
            }
        }

        return (await res.json()) as TCJSONResponse;
    }
}
