/* Generated by pecans-spec. Do not edit. */
import type { Client } from "./client";

export class Module {
    #client: Client;

    protected get client(): Client {
        return this.#client;
    }

    public constructor(client: Client) {
        this.#client = client;
    }
}
