/* Generated by pecans-spec. Do not edit. */
import { Module } from "../module";
import { LoginResponse } from "../generated/types";

export class AuthModule extends Module {
    public async login(username: string, password: string, client: string = "web"): Promise<LoginResponse> {
        return await this.client._call<LoginResponse>(
            "auth.login",
            {
                "nameOrEmail": username,
                "password": password,
                "client": client,
            },
        );
    }
}
