#!/usr/bin/env bun
import { compile, NodeHost, resolveEncodedName, serializeValueAsJson } from "@typespec/compiler";
import { compile as jsonToTs } from "json-schema-to-typescript";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "../../..");
const SPEC = join(import.meta.dir, "..", "main.tsp");
const SCHEMA = join(import.meta.dir, "../dist/@typespec/json-schema/pecans.json");
const GEN = join(ROOT, "sdks/typescript/src/generated");
const BANNER = "/* Generated by pecans-spec. Do not edit. */\n";

const RPC = Symbol.for("pecans.rpc");
const CONSTANT = Symbol.for("pecans.constant");
const ALSO = Symbol.for("pecans.also");
const JOIN = Symbol.for("pecans.join");
const ZIP = Symbol.for("pecans.zip");
const FROM_INPUT = Symbol.for("pecans.fromInput");
const FROM_RESULT = Symbol.for("pecans.fromResult");

const NUMERIC = new Set([
    "int8",
    "int16",
    "int32",
    "int64",
    "integer",
    "safeint",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "float",
    "float32",
    "float64",
    "numeric",
    "decimal",
    "decimal128",
]);

function tsType(type: any, enumsUsed: Set<any>): string {
    switch (type.kind) {
        case "Scalar":
            if (NUMERIC.has(type.name)) {
                return "number";
            }

            if (type.name === "boolean") {
                return "boolean";
            }

            return "string";

        case "Enum":
            enumsUsed.add(type);
            return type.name;

        case "Model":
            if (type.name === "Array" && type.indexer) {
                return `${tsType(type.indexer.value, enumsUsed)}[]`;
            }

            return type.name;

        default:
            return "any";
    }
}

function jsValue(program: any, value: any): unknown {
    if (value === null || value === undefined) {
        return value;
    }

    if (typeof value === "object" && "valueKind" in value) {
        return serializeValueAsJson(program, value, value.type);
    }

    return value;
}

async function genTypes(exclude: Set<string>): Promise<void> {
    const normalize = (node: unknown): unknown => {
        if (Array.isArray(node)) {
            return node.map(normalize);
        }

        if (node && typeof node === "object") {
            const out: Record<string, unknown> = {};

            for (const [key, value] of Object.entries(node)) {
                if (key === "$id" || key === "$schema") {
                    continue;
                }

                if (key === "$ref" && typeof value === "string" && value.endsWith(".json")) {
                    out.$ref = `#/$defs/${value.slice(0, -".json".length)}`;
                    continue;
                }

                out[key] = normalize(value);
            }

            return out;
        }

        return node;
    };

    const bundle = normalize(await Bun.file(SCHEMA).json()) as { $defs: Record<string, unknown> };

    for (const name of exclude) {
        delete bundle.$defs[name];
    }

    const root = {
        title: "PecansSchemaRoot",
        type: "object",
        additionalProperties: false,
        properties: Object.fromEntries(
            Object.keys(bundle.$defs).map((n) => [n, { $ref: `#/$defs/${n}` }]),
        ),
        $defs: bundle.$defs,
    };

    let ts = await jsonToTs(root as never, "PecansSchemaRoot", {
        bannerComment: BANNER,
        additionalProperties: false,
        declareExternallyReferenced: true,
    });

    ts = ts.replace(/export interface PecansSchemaRoot \{[\s\S]*?\n\}\n?/, "");
    await writeFile(join(GEN, "types.ts"), ts);
}

interface GenParam {
    name: string;
    tsType: string;
    optional: boolean;
    defaultCode?: string;
    wireName: string;
    also: string[];
    joinSep?: string;
}

interface GenZip {
    callMethod: string;
    input: string;
    project: string;
    key: string;
    results: string;
    element: string;
    fields: { name: string; source: string }[];
}

interface GenOp {
    method: string;
    fn: string;
    params: GenParam[];
    constants: Record<string, unknown>;
    response: string;
    decode?: string;
    zip?: GenZip;
}

interface GenModule {
    name: string;
    className: string;
    ops: GenOp[];
    responses: Set<string>;
    enums: Set<string>;
    decoders: Set<string>;
}

/** All properties of a model, own plus inherited, base-first. */
function collectProps(model: any): any[] {
    const props: any[] = [];

    if (model.baseModel) {
        props.push(...collectProps(model.baseModel));
    }

    for (const p of model.properties.values()) {
        props.push(p);
    }

    return props;
}

/** The named Pecans model a property carries (unwrapping arrays), if any. */
function propModel(type: any): { model: any | undefined; isArray: boolean } {
    if (type?.kind === "Model" && type.name === "Array" && type.indexer) {
        const el = type.indexer.value;
        const named = el?.kind === "Model" && el.name && el.name !== "Array" ? el : undefined;

        return {
            model: named,
            isArray: true,
        };
    }

    if (type?.kind === "Model" && type.name && type.name !== "Array") {
        return {
            model: type,
            isArray: false,
        };
    }

    return {
        model: undefined,
        isArray: false,
    };
}

/** A model needs a decoder if any field is renamed on the wire, transitively. */
function needsDecode(program: any, model: any, memo: Map<any, boolean>): boolean {
    if (memo.has(model)) {
        return memo.get(model)!;
    }

    memo.set(model, false);

    let result = false;

    for (const p of collectProps(model)) {
        if (resolveEncodedName(program, p, "application/json") !== p.name) {
            result = true;
            break;
        }

        const { model: m } = propModel(p.type);

        if (m && needsDecode(program, m, memo)) {
            result = true;
            break;
        }
    }

    memo.set(model, result);
    return result;
}

function genDecoder(program: any, model: any, memo: Map<any, boolean>): string {
    const lines = collectProps(model).map((p: any) => {
        const wire = resolveEncodedName(program, p, "application/json");
        const key = JSON.stringify(wire);
        const { model: m, isArray } = propModel(p.type);

        let expr: string;

        if (m && needsDecode(program, m, memo)) {
            expr = isArray
                ? `(raw[${key}] ?? []).map(decode${m.name})`
                : `raw[${key}] == null ? raw[${key}] : decode${m.name}(raw[${key}])`;
        } else {
            expr = `raw[${key}]`;
        }

        return `        ${p.name}: ${expr},`;
    });

    return `export function decode${model.name}(raw: any): ${model.name} {
    return {
${lines.join("\n")}
    };
}`;
}

function genDecodersFile(program: any, models: any[], memo: Map<any, boolean>): string {
    const names = [...new Set(models.map((m) => m.name))].sort();
    const body = models
        .slice()
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((m) => genDecoder(program, m, memo))
        .join("\n\n");

    return `${BANNER}import { ${names.join(", ")} } from "./types";\n\n${body}\n`;
}

function signature(params: GenParam[]): string {
    return params
        .map((p) => {
            if (p.defaultCode !== undefined) {
                return `${p.name}: ${p.tsType} = ${p.defaultCode}`;
            }

            if (p.optional) {
                return `${p.name}?: ${p.tsType}`;
            }

            return `${p.name}: ${p.tsType}`;
        })
        .join(", ");
}

function payloadLiteral(op: GenOp): string {
    const entries: string[] = [];

    for (const p of op.params) {
        const value =
            p.joinSep !== undefined ? `${p.name}.join(${JSON.stringify(p.joinSep)})` : p.name;

        entries.push(`                ${JSON.stringify(p.wireName)}: ${value},`);

        for (const alt of p.also) {
            entries.push(`                ${JSON.stringify(alt)}: ${value},`);
        }
    }

    for (const [key, value] of Object.entries(op.constants)) {
        entries.push(`                ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
    }

    if (entries.length === 0) {
        return "{}";
    }

    return `{\n${entries.join("\n")}\n            }`;
}

function genZipMethod(op: GenOp): string {
    const z = op.zip!;
    const combine = z.fields.map((f) => `${f.name}: ${f.source}`).join(", ");

    return `    public async ${op.method}(${signature(op.params)}): Promise<${z.element}[]> {
        const res = await this.${z.callMethod}(${z.input}.map((x) => x.${z.project}));

        return joinBy(
            ${z.input},
            res.${z.results} ?? [],
            (input) => input.${z.key},
            (r) => r.${z.key},
            (r, input) => ({ ${combine} }),
        );
    }`;
}

function genCallMethod(op: GenOp): string {
    return `    public ${op.method}(${signature(op.params)}): Call<${op.response}> {
        return new Call<${op.response}>(this.client, {
            fn: ${JSON.stringify(op.fn)},
            payload: ${payloadLiteral(op)},
        }${op.decode ? `, ${op.decode}` : ""});
    }`;
}

function genModuleFile(mod: GenModule): string {
    const hasCall = mod.ops.some((op) => !op.zip);
    const hasZip = mod.ops.some((op) => op.zip);
    const runtimeImports = hasCall ? "Call, Module" : "Module";

    const imports = [`import { ${runtimeImports} } from "../../runtime";`];

    if (hasZip) {
        imports.push(`import { joinBy } from "../../runtime/join";`);
    }

    imports.push(`import { ${[...mod.responses].sort().join(", ")} } from "../types";`);

    if (mod.enums.size > 0) {
        imports.push(`import { ${[...mod.enums].sort().join(", ")} } from "../enums";`);
    }

    if (mod.decoders.size > 0) {
        imports.push(`import { ${[...mod.decoders].sort().join(", ")} } from "../decoders";`);
    }

    const methods = mod.ops
        .map((op) => (op.zip ? genZipMethod(op) : genCallMethod(op)))
        .join("\n\n");

    return `${BANNER}${imports.join("\n")}

export class ${mod.className} extends Module {
${methods}
}
`;
}

function genEnums(program: any, enums: Map<string, any>): string {
    const blocks = [...enums.values()].map((en) => {
        const members = [...en.members.values()]
            .map(
                (m: any) =>
                    `    ${m.name} = ${JSON.stringify(jsValue(program, m.value ?? m.name))},`,
            )
            .join("\n");
        return `export enum ${en.name} {\n${members}\n}`;
    });

    return `${BANNER}${blocks.join("\n\n")}\n`;
}

function genClient(mods: GenModule[]): string {
    const imports = mods
        .map((m) => `import { ${m.className} } from "./modules/${m.name}";`)
        .join("\n");
    const fields = mods.map((m) => `    #${m.name}: ${m.className};`).join("\n");
    const getters = mods
        .map(
            (m) =>
                `    public get ${m.name}(): ${m.className} {\n        return this.#${m.name};\n    }`,
        )
        .join("\n\n");
    const init = mods.map((m) => `        this.#${m.name} = new ${m.className}(this);`).join("\n");

    return `${BANNER}import { BaseClient } from "../runtime";
${imports}

export class Client extends BaseClient {
${fields}

    public constructor(auth?: string) {
        super(auth);
${init}
    }

${getters}
}
`;
}

function genIndex(mods: GenModule[], hasDecoders: boolean): string {
    return `${BANNER}export * from "./types";
export * from "./enums";
${hasDecoders ? `export * from "./decoders";\n` : ""}export * from "./client";
${mods.map((m) => `export * from "./modules/${m.name}";`).join("\n")}
`;
}

async function main(): Promise<void> {
    const program = await compile(NodeHost, SPEC, {});
    const errors = program.diagnostics.filter((d) => d.severity === "error");

    if (errors.length) {
        for (const d of errors) {
            console.error(d.code, d.message);
        }

        throw new Error("spec has errors");
    }

    const rpcMap = program.stateMap(RPC);
    const constMap = program.stateMap(CONSTANT);
    const alsoMap = program.stateMap(ALSO);
    const joinMap = program.stateMap(JOIN);
    const zipMap = program.stateMap(ZIP);
    const fromInputMap = program.stateMap(FROM_INPUT);
    const fromResultMap = program.stateMap(FROM_RESULT);

    const ns = program.getGlobalNamespaceType().namespaces.get("Pecans");
    if (!ns) {
        throw new Error("namespace Pecans not found");
    }

    const enumsUsed = new Map<string, any>();
    const mods: GenModule[] = [];
    const responseTypes = new Set<any>();

    for (const iface of ns.interfaces.values()) {
        const mod: GenModule = {
            name: iface.name.toLowerCase(),
            className: `${iface.name}Module`,
            ops: [],
            responses: new Set(),
            enums: new Set(),
            decoders: new Set(),
        };

        for (const op of iface.operations.values()) {
            const zipCfg = zipMap.get(op);
            const fn = rpcMap.get(op);
            if (!fn && !zipCfg) {
                continue;
            }

            const localEnums = new Set<any>();

            const params: GenParam[] = [...op.parameters.properties.values()].map((prm: any) => {
                const t = tsType(prm.type, localEnums);
                const wireName = resolveEncodedName(program, prm, "application/json");
                const also = (alsoMap.get(prm) as string[] | undefined) ?? [];
                const joinSep = joinMap.get(prm) as string | undefined;

                let defaultCode: string | undefined;
                if (prm.defaultValue) {
                    defaultCode = JSON.stringify(jsValue(program, prm.defaultValue));
                }

                return {
                    name: prm.name,
                    tsType: t,
                    optional: prm.optional,
                    defaultCode,
                    wireName,
                    also,
                    joinSep,
                };
            });

            for (const en of localEnums) {
                enumsUsed.set(en.name, en);
                mod.enums.add(en.name);
            }

            if (zipCfg) {
                const cfg = jsValue(program, zipCfg) as Record<string, string>;
                const element = (op.returnType as any).indexer.value;

                mod.responses.add(element.name);

                for (const prm of op.parameters.properties.values()) {
                    const { model } = propModel((prm as any).type);

                    if (model) {
                        mod.responses.add(model.name);
                    }
                }

                const fields = [...element.properties.values()].map((pr: any) => {
                    const fromResult = fromResultMap.get(pr) as string | undefined;
                    if (fromResult !== undefined) {
                        return { name: pr.name, source: `r.${fromResult}` };
                    }
                    const fromInput = fromInputMap.get(pr) as string | null | undefined;
                    return { name: pr.name, source: fromInput ? `input.${fromInput}` : "input" };
                });

                const zip: GenZip = {
                    callMethod: cfg.call,
                    input: cfg.input,
                    project: cfg.project,
                    key: cfg.key,
                    results: cfg.results,
                    element: element.name,
                    fields,
                };

                mod.ops.push({
                    method: op.name,
                    fn: "",
                    params,
                    constants: {},
                    response: element.name,
                    zip,
                });
                continue;
            }

            const response = (op.returnType as any).name ?? "TCResponse";
            mod.responses.add(response);
            if ((op.returnType as any).kind === "Model") {
                responseTypes.add(op.returnType);
            }

            const rawConst = constMap.get(op);
            const constants = (rawConst ? jsValue(program, rawConst) : {}) as Record<
                string,
                unknown
            >;
            mod.ops.push({
                method: op.name,
                fn: fn as string,
                params,
                constants,
                response,
            });
        }

        if (mod.ops.length > 0) {
            mods.push(mod);
        }
    }

    mods.sort((a, b) => a.name.localeCompare(b.name));

    const memo = new Map<any, boolean>();
    const decoderModels: any[] = [];
    const decodable = new Set<string>();
    const seen = new Set<any>();
    const queue = [...responseTypes];

    while (queue.length) {
        const model = queue.pop();

        if (!model || seen.has(model)) {
            continue;
        }

        seen.add(model);

        if (!needsDecode(program, model, memo)) {
            continue;
        }

        decoderModels.push(model);
        decodable.add(model.name);

        for (const p of collectProps(model)) {
            const { model: m } = propModel(p.type);

            if (m) {
                queue.push(m);
            }
        }
    }

    for (const mod of mods) {
        for (const op of mod.ops) {
            if (decodable.has(op.response)) {
                op.decode = `decode${op.response}`;
                mod.decoders.add(op.decode);
            }
        }
    }

    await rm(GEN, { recursive: true, force: true });
    await mkdir(join(GEN, "modules"), { recursive: true });

    await genTypes(new Set(enumsUsed.keys()));
    await writeFile(join(GEN, "enums.ts"), genEnums(program, enumsUsed));

    if (decoderModels.length > 0) {
        await writeFile(join(GEN, "decoders.ts"), genDecodersFile(program, decoderModels, memo));
    }

    await writeFile(join(GEN, "client.ts"), genClient(mods));
    await writeFile(join(GEN, "index.ts"), genIndex(mods, decoderModels.length > 0));

    for (const mod of mods) {
        await writeFile(join(GEN, "modules", `${mod.name}.ts`), genModuleFile(mod));
    }

    console.log(`generated ${mods.length} modules -> ${GEN}`);
}

await main();
