#!/usr/bin/env bun
import {
    compile,
    NodeHost,
    resolveEncodedName,
    serializeValueAsJson,
} from "@typespec/compiler";
import { compile as jsonToTs } from "json-schema-to-typescript";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "../../..");
const SPEC = join(import.meta.dir, "..", "main.tsp");
const SCHEMA = join(import.meta.dir, "../dist/@typespec/json-schema/pecans.json");
const OUT = join(ROOT, "sdks/typescript/src");
const BANNER = "/* Generated by pecans-spec. Do not edit. */\n";

const RPC = Symbol.for("pecans.rpc");
const CONSTANT = Symbol.for("pecans.constant");
const ALSO = Symbol.for("pecans.also");

const NUMERIC = new Set([
    "int8", "int16", "int32", "int64", "integer", "safeint",
    "uint8", "uint16", "uint32", "uint64", "float", "float32", "float64",
    "numeric", "decimal", "decimal128",
]);

function tsType(type: any, enumsUsed: Set<any>): string {
    switch (type.kind) {
        case "Scalar":
            if (NUMERIC.has(type.name)) return "number";
            if (type.name === "boolean") return "boolean";
            return "string";
        case "Enum":
            enumsUsed.add(type);
            return type.name;
        case "Model":
            return type.name;
        default:
            return "any";
    }
}

function jsValue(program: any, value: any): unknown {
    if (value === null || value === undefined) return value;
    if (typeof value === "object" && "valueKind" in value) {
        return serializeValueAsJson(program, value, value.type);
    }
    return value;
}

async function genTypes(exclude: Set<string>): Promise<void> {
    const normalize = (node: unknown): unknown => {
        if (Array.isArray(node)) return node.map(normalize);
        if (node && typeof node === "object") {
            const out: Record<string, unknown> = {};
            for (const [key, value] of Object.entries(node)) {
                if (key === "$id" || key === "$schema") continue;
                if (key === "$ref" && typeof value === "string" && value.endsWith(".json")) {
                    out.$ref = `#/$defs/${value.slice(0, -".json".length)}`;
                    continue;
                }
                out[key] = normalize(value);
            }
            return out;
        }
        return node;
    };
    const bundle = normalize(await Bun.file(SCHEMA).json()) as { $defs: Record<string, unknown> };
    for (const name of exclude) delete bundle.$defs[name];
    const root = {
        title: "PecansSchemaRoot",
        type: "object",
        additionalProperties: false,
        properties: Object.fromEntries(
            Object.keys(bundle.$defs).map((n) => [n, { $ref: `#/$defs/${n}` }]),
        ),
        $defs: bundle.$defs,
    };
    let ts = await jsonToTs(root as never, "PecansSchemaRoot", {
        bannerComment: BANNER,
        additionalProperties: false,
        declareExternallyReferenced: true,
    });
    ts = ts.replace(/export interface PecansSchemaRoot \{[\s\S]*?\n\}\n?/, "");
    await writeFile(join(OUT, "generated/types.ts"), ts);
}

interface GenParam {
    name: string;
    tsType: string;
    optional: boolean;
    defaultCode?: string;
    wireName: string;
    also: string[];
}

interface GenOp {
    method: string;
    fn: string;
    params: GenParam[];
    constants: Record<string, unknown>;
    response: string;
}

interface GenModule {
    name: string;
    className: string;
    ops: GenOp[];
    responses: Set<string>;
    enums: Set<string>;
}

function signature(params: GenParam[]): string {
    return params
        .map((p) => {
            if (p.defaultCode !== undefined) return `${p.name}: ${p.tsType} = ${p.defaultCode}`;
            if (p.optional) return `${p.name}?: ${p.tsType}`;
            return `${p.name}: ${p.tsType}`;
        })
        .join(", ");
}

function payloadLiteral(op: GenOp): string {
    const entries: string[] = [];
    for (const p of op.params) {
        entries.push(`                ${JSON.stringify(p.wireName)}: ${p.name},`);
        for (const alt of p.also) entries.push(`                ${JSON.stringify(alt)}: ${p.name},`);
    }
    for (const [key, value] of Object.entries(op.constants)) {
        entries.push(`                ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
    }
    if (entries.length === 0) return "{}";
    return `{\n${entries.join("\n")}\n            }`;
}

function genModuleFile(mod: GenModule): string {
    const imports = [
        `import { Module } from "../module";`,
        `import { ${[...mod.responses].sort().join(", ")} } from "../generated/types";`,
    ];
    if (mod.enums.size > 0) {
        imports.push(`import { ${[...mod.enums].sort().join(", ")} } from "../enums";`);
    }
    const methods = mod.ops
        .map(
            (op) => `    public async ${op.method}(${signature(op.params)}): Promise<${op.response}> {
        return await this.client._call<${op.response}>(
            ${JSON.stringify(op.fn)},
            ${payloadLiteral(op)},
        );
    }`,
        )
        .join("\n\n");
    return `${BANNER}${imports.join("\n")}

export class ${mod.className} extends Module {
${methods}
}
`;
}

function genEnums(program: any, enums: Map<string, any>): string {
    const blocks = [...enums.values()].map((en) => {
        const members = [...en.members.values()]
            .map((m: any) => `    ${m.name} = ${JSON.stringify(jsValue(program, m.value ?? m.name))},`)
            .join("\n");
        return `export enum ${en.name} {\n${members}\n}`;
    });
    return `${BANNER}${blocks.join("\n\n")}\n`;
}

const STATIC_TYPES = `${BANNER}import { TCProfile } from "./generated/types";

export interface MethodCall {
    readonly fn: string;
    readonly payload: { [key: string]: any };
}

export interface TCJSONResponse {
    readonly ok: boolean;
    readonly responses: TCResponseRaw[];
    readonly profiles?: TCProfile[];
    readonly loginId?: string;
    readonly auth?: string;
    readonly ver?: string;
}

export interface TCResponseRaw {
    [key: string]: any;
}
`;

const STATIC_MODULE = `${BANNER}import type { Client } from "./client";

export class Module {
    #client: Client;

    protected get client(): Client {
        return this.#client;
    }

    public constructor(client: Client) {
        this.#client = client;
    }
}
`;

function genClient(mods: GenModule[]): string {
    const imports = mods.map((m) => `import { ${m.className} } from "./${m.name}";`).join("\n");
    const fields = mods.map((m) => `    #${m.name}: ${m.className};`).join("\n");
    const getters = mods
        .map((m) => `    public get ${m.name}(): ${m.className} {\n        return this.#${m.name};\n    }`)
        .join("\n\n");
    const init = mods.map((m) => `        this.#${m.name} = new ${m.className}(this);`).join("\n");

    return `${BANNER}import { MethodCall, TCJSONResponse } from "./types";
import { TCProfile } from "./generated/types";
${imports}

export class ResponseParseError {
    public readonly name: string = "ResponseParseError";
    public readonly message: string = "Failed to parse API response as JSON";
    public readonly responseText: string;
    public readonly cause?: unknown;

    public constructor(responseText: string, cause?: unknown) {
        this.responseText = responseText;
        if (cause !== undefined) {
            this.cause = cause;
        }
    }
}

interface QueuedCall {
    methodCall: MethodCall;
    resolve: (value: unknown) => void;
    reject: (reason: unknown) => void;
}

export class Client {
    static readonly BASE_URI = "https://api.twocansandstring.com/api";
    static readonly VERSION = "1.68";

${fields}

    #activeBatch: QueuedCall[] | null = null;

    public profileCache: { [key: string]: TCProfile } = {};

    public authToken?: string;

    public agent: string = "pecans";

    public shouldTrimErrors: boolean = true;

${getters}

    public get isBatching(): boolean {
        return this.#activeBatch !== null;
    }

    public constructor(auth?: string) {
        this.authToken = auth;
${init}
    }

    /** @internal */
    public _call<T>(methodName: string, args: { [key: string]: any }): Promise<T> {
        const methodCall: MethodCall = { fn: methodName, payload: args };

        if (this.#activeBatch !== null) {
            const batch = this.#activeBatch;
            return new Promise<T>((resolve, reject) => {
                batch.push({ methodCall, resolve: resolve as (value: unknown) => void, reject });
            });
        }

        return this.#send([methodCall]).then((res) => this.#build<T>(res, 0));
    }

    public beginBatch(): void {
        this.#activeBatch ??= [];
    }

    public async endBatch(): Promise<void> {
        const batch = this.#activeBatch;
        this.#activeBatch = null;

        if (batch === null || batch.length === 0) {
            return;
        }

        try {
            const res = await this.#send(batch.map((call) => call.methodCall));
            batch.forEach((call, index) => call.resolve(this.#build(res, index)));
        } catch (reason) {
            batch.forEach((call) => call.reject(reason));
        }
    }

    #build<T>(res: TCJSONResponse | undefined, index: number): T {
        res?.profiles?.forEach((profile) => {
            this.profileCache[profile.id] = profile;
        });

        return {
            ok: res?.ok ?? false,
            ...(res?.responses?.[index] ?? {}),
            profiles: res?.profiles,
        } as T;
    }

    async #send(requests: MethodCall[]): Promise<TCJSONResponse | undefined> {
        const headers: { [key: string]: string } = {
            "Content-Type": "application/json",
            "User-Agent": this.agent,
        };

        if (this.authToken != undefined) {
            headers["Cookie"] = "twocansandstring_com_auth2=" + this.authToken;
        }

        const res = await fetch(Client.BASE_URI, {
            method: "POST",
            headers,
            body: JSON.stringify({ auth: this.authToken, requests }),
        });

        if (!res.ok) {
            return Promise.reject();
        }

        if (this.shouldTrimErrors) {
            let text = await res.text();
            text = text.replace(/^(?:.*\\n)*{/, "{");
            try {
                return JSON.parse(text) as TCJSONResponse;
            } catch (cause) {
                throw new ResponseParseError(text, cause);
            }
        }

        return (await res.json()) as TCJSONResponse;
    }
}
`;
}

function genIndex(mods: GenModule[]): string {
    return `${BANNER}export * from "./client";
export * from "./module";
export * from "./types";
export * from "./enums";
export * from "./generated/types";
${mods.map((m) => `export * from "./${m.name}";`).join("\n")}
`;
}

async function main(): Promise<void> {
    const program = await compile(NodeHost, SPEC, {});
    const errors = program.diagnostics.filter((d) => d.severity === "error");
    if (errors.length) {
        for (const d of errors) console.error(d.code, d.message);
        throw new Error("spec has errors");
    }

    const rpcMap = program.stateMap(RPC);
    const constMap = program.stateMap(CONSTANT);
    const alsoMap = program.stateMap(ALSO);

    const ns = program.getGlobalNamespaceType().namespaces.get("Pecans");
    if (!ns) throw new Error("namespace Pecans not found");

    const enumsUsed = new Map<string, any>();
    const mods: GenModule[] = [];

    for (const iface of ns.interfaces.values()) {
        const mod: GenModule = {
            name: iface.name.toLowerCase(),
            className: `${iface.name}Module`,
            ops: [],
            responses: new Set(),
            enums: new Set(),
        };
        for (const op of iface.operations.values()) {
            const fn = rpcMap.get(op);
            if (!fn) continue;
            const localEnums = new Set<any>();
            const params: GenParam[] = [...op.parameters.properties.values()].map((prm: any) => {
                const t = tsType(prm.type, localEnums);
                const wireName = resolveEncodedName(program, prm, "application/json");
                const also = (alsoMap.get(prm) as string[] | undefined) ?? [];
                let defaultCode: string | undefined;
                if (prm.defaultValue) {
                    defaultCode = JSON.stringify(jsValue(program, prm.defaultValue));
                }
                return { name: prm.name, tsType: t, optional: prm.optional, defaultCode, wireName, also };
            });
            for (const en of localEnums) {
                enumsUsed.set(en.name, en);
                mod.enums.add(en.name);
            }
            const response = (op.returnType as any).name ?? "TCResponse";
            mod.responses.add(response);
            const rawConst = constMap.get(op);
            const constants = (rawConst ? jsValue(program, rawConst) : {}) as Record<string, unknown>;
            mod.ops.push({ method: op.name, fn: fn as string, params, constants, response });
        }
        if (mod.ops.length > 0) mods.push(mod);
    }
    mods.sort((a, b) => a.name.localeCompare(b.name));

    await rm(OUT, { recursive: true, force: true });
    await mkdir(join(OUT, "generated"), { recursive: true });

    await genTypes(new Set(enumsUsed.keys()));
    await writeFile(join(OUT, "types.ts"), STATIC_TYPES);
    await writeFile(join(OUT, "module.ts"), STATIC_MODULE);
    await writeFile(join(OUT, "enums.ts"), genEnums(program, enumsUsed));
    await writeFile(join(OUT, "client.ts"), genClient(mods));
    await writeFile(join(OUT, "index.ts"), genIndex(mods));
    for (const mod of mods) {
        await mkdir(join(OUT, mod.name), { recursive: true });
        await writeFile(join(OUT, mod.name, "index.ts"), genModuleFile(mod));
    }

    console.log(`generated ${mods.length} modules -> ${OUT}`);
}

await main();
