/* Generated by pecans-spec. Do not edit. */
import { Module } from "../module";
import { NotifySyncResponse, WhosOnlineResponse } from "../generated/types";
import { Feature } from "../enums";

export class NotifyModule extends Module {
    public async sync(feature: Feature): Promise<NotifySyncResponse> {
        return await this.client._call<NotifySyncResponse>(
            "notify.sync",
            {
                "feature": feature,
            },
        );
    }

    public async fetchOnlineUsers(feature: Feature): Promise<WhosOnlineResponse> {
        return await this.client._call<WhosOnlineResponse>(
            "notify.whosonline",
            {
                "feature": feature,
            },
        );
    }
}
