/* Generated by pecans-spec. Do not edit. */
import { Module } from "../module";
import { SaveDrawingResponse, TCResponse, ViewDrawingDataResponse } from "../generated/types";

export class DrawingModule extends Module {
    public async saveDrawing(data: string, makeActive: boolean = false): Promise<SaveDrawingResponse> {
        return await this.client._call<SaveDrawingResponse>(
            "legacy.drawing",
            {
                "data": data,
                "makeActive": makeActive,
                "action": "save",
            },
        );
    }

    public async viewDrawingData(imageId: string): Promise<ViewDrawingDataResponse> {
        return await this.client._call<ViewDrawingDataResponse>(
            "legacy.drawing",
            {
                "imageId": imageId,
                "action": "initial-image-data",
            },
        );
    }

    public async sendDrawing(imageId: string, receiver: string): Promise<TCResponse> {
        return await this.client._call<TCResponse>(
            "drawing.send",
            {
                "imageId": imageId,
                "receiver": receiver,
            },
        );
    }
}
