import { join } from "node:path";
import type { Backend, GenFile } from "../emit";
import type { IrEnum, IrModule, IrProgram, IrType, IrZipField } from "../ir";

const ROOT = join(import.meta.dir, "../../../..");
const OUT = join(ROOT, "sdks/python/src/pecans/generated");
const BANNER = "# Generated by pecans-spec. Do not edit.\n";

function pyType(type: IrType): string {
    switch (type.kind) {
        case "int":
            return "int";

        case "float":
            return "float";

        case "bool":
            return "bool";

        case "string":
            return "str";

        case "enum":
        case "model":
            return type.name;

        case "array":
            return `list[${pyType(type.element)}]`;

        case "nullable":
            return `${pyType(type.inner)} | None`;

        case "dict":
            return "dict[str, Any]";

        default:
            return "Any";
    }
}

/** Render a JS value as a Python literal. */
function pyLiteral(value: unknown): string {
    if (value === null || value === undefined) {
        return "None";
    }

    if (typeof value === "boolean") {
        return value ? "True" : "False";
    }

    if (typeof value === "number") {
        return String(value);
    }

    if (typeof value === "string") {
        return JSON.stringify(value);
    }

    if (Array.isArray(value)) {
        return `[${value.map(pyLiteral).join(", ")}]`;
    }

    const entries = Object.entries(value as Record<string, unknown>).map(
        ([key, val]) => `${JSON.stringify(key)}: ${pyLiteral(val)}`,
    );

    return `{${entries.join(", ")}}`;
}

/** Enum names referenced anywhere in a type, recursing into arrays. */
function enumsInType(type: IrType, out: Set<string>): void {
    if (type.kind === "enum") {
        out.add(type.name);
    }

    if (type.kind === "array") {
        enumsInType(type.element, out);
    }

    if (type.kind === "nullable") {
        enumsInType(type.inner, out);
    }
}

function className(mod: IrModule): string {
    return `${mod.interfaceName}Module`;
}

function decodeName(model: string): string {
    return `decode${model}`;
}

function zipSource(field: IrZipField): string {
    if (field.from === "result") {
        return `r[${JSON.stringify(field.field)}]`;
    }

    if (field.from === "input") {
        return `inp[${JSON.stringify(field.field)}]`;
    }

    return "inp";
}

/** Render a Google-style docstring (indented into the method body), or "" if undocumented. */
function docstring(op: IrModule["ops"][number]): string {
    const flat = (s: string) => s.replace(/\s*\n\s*/g, " ");
    const lines: string[] = [];

    if (op.doc) {
        lines.push(...op.doc.split("\n"));
    }

    const args = op.params.filter((p) => p.doc);

    if (args.length > 0) {
        if (lines.length > 0) {
            lines.push("");
        }

        lines.push("Args:");

        for (const p of args) {
            lines.push(`    ${p.name}: ${flat(p.doc!)}`);
        }
    }

    if (op.returnsDoc) {
        if (lines.length > 0) {
            lines.push("");
        }

        lines.push("Returns:", `    ${flat(op.returnsDoc)}`);
    }

    if (lines.length === 0) {
        return "";
    }

    if (lines.length === 1) {
        return `        """${lines[0]}"""\n`;
    }

    const rest = lines
        .slice(1)
        .map((l) => (l ? `        ${l}` : ""))
        .join("\n");

    return `        """${lines[0]}\n${rest}\n        """\n`;
}

function signature(mod: IrModule, op: IrModule["ops"][number]): string {
    const parts = ["self"];

    for (const p of op.params) {
        if (p.hasDefault) {
            parts.push(`${p.name}: ${pyType(p.type)} = ${pyLiteral(p.default)}`);
        } else if (p.optional) {
            parts.push(`${p.name}: ${pyType(p.type)} | None = None`);
        } else {
            parts.push(`${p.name}: ${pyType(p.type)}`);
        }
    }

    return parts.join(", ");
}

function payloadLiteral(op: IrModule["ops"][number]): string {
    const entries: string[] = [];

    for (const p of op.params) {
        if (p.embed !== undefined) {
            entries.push(
                `                ${JSON.stringify(p.embed)}: json.dumps(${p.name}, separators=(",", ":")),`,
            );
            continue;
        }

        let value: string;

        if (p.joinSep !== undefined) {
            value = `${JSON.stringify(p.joinSep)}.join(str(v) for v in ${p.name})`;
        } else if (p.stringify) {
            value = p.type.kind === "bool" ? `("1" if ${p.name} else "0")` : `str(${p.name})`;
        } else {
            value = p.name;
        }

        entries.push(`                ${JSON.stringify(p.wireName)}: ${value},`);

        for (const alt of p.also) {
            entries.push(`                ${JSON.stringify(alt)}: ${value},`);
        }
    }

    for (const [key, value] of Object.entries(op.constants)) {
        entries.push(`                ${JSON.stringify(key)}: ${pyLiteral(value)},`);
    }

    if (entries.length === 0) {
        return "{}";
    }

    return `{\n${entries.join("\n")}\n            }`;
}

function zipMethod(mod: IrModule, op: IrModule["ops"][number]): string {
    const z = op.zip!;
    const combine = z.fields.map((f) => `${JSON.stringify(f.name)}: ${zipSource(f)}`).join(", ");

    return `    async def ${op.method}(${signature(mod, op)}) -> list[${z.element}]:
${docstring(op)}        res = await self.${z.callMethod}([x[${JSON.stringify(z.project)}] for x in ${z.input}])

        return join_by(
            ${z.input},
            res.get(${JSON.stringify(z.results)}) or [],
            lambda inp: inp[${JSON.stringify(z.key)}],
            lambda r: r[${JSON.stringify(z.key)}],
            lambda r, inp: {${combine}},
        )`;
}

function callMethod(mod: IrModule, op: IrModule["ops"][number]): string {
    const decodeArg = op.decodeModel ? `,\n            ${decodeName(op.decodeModel)},` : "";

    return `    def ${op.method}(${signature(mod, op)}) -> Call[${op.response}]:
${docstring(op)}        return Call(
            self.client,
            MethodCall(
                fn=${JSON.stringify(op.fn)},
                payload=${payloadLiteral(op)},
            )${decodeArg}
        )`;
}

export const python: Backend = {
    outDir: OUT,
    ext: "py",
    indexFile: "__init__.py",

    renderTypes(ir: IrProgram): string {
        const enumsUsed = new Set<string>();

        const blocks = ir.models.map((model) => {
            const fields = model.fields.map((p) => {
                enumsInType(p.type, enumsUsed);

                const t = pyType(p.type);
                const ref = p.optional ? `NotRequired[${JSON.stringify(t)}]` : JSON.stringify(t);

                return `        ${JSON.stringify(p.name)}: ${ref},`;
            });

            return `${model.name} = TypedDict(
    ${JSON.stringify(model.name)},
    {
${fields.join("\n")}
    },
)`;
        });

        const imports = ["from typing import Any, NotRequired, TypedDict"];

        if (enumsUsed.size > 0) {
            imports.push(`from .enums import ${[...enumsUsed].sort().join(", ")}`);
        }

        return `${BANNER}from __future__ import annotations

${imports.join("\n")}


${blocks.join("\n\n\n")}
`;
    },

    renderEnums(ir: IrProgram): string {
        const used = new Set<string>();

        for (const mod of ir.modules) {
            for (const name of mod.enums) {
                used.add(name);
            }
        }

        for (const model of ir.models) {
            for (const field of model.fields) {
                enumsInType(field.type, used);
            }
        }

        const blocks = ir.enums
            .filter((en) => used.has(en.name))
            .map((en: IrEnum) => {
                const members = en.members
                    .map((m) => `    ${m.name} = ${pyLiteral(m.value)}`)
                    .join("\n");

                return `class ${en.name}(str, Enum):\n${members}`;
            });

        return `${BANNER}from enum import Enum


${blocks.join("\n\n\n")}
`;
    },

    renderDecoders(ir: IrProgram): string {
        const names = [...new Set(ir.decoders.map((d) => d.model))].sort();
        const body = ir.decoders
            .slice()
            .sort((a, b) => a.model.localeCompare(b.model))
            .map((d) => {
                const lines = d.fields.map((f) => {
                    const key = JSON.stringify(f.wireName);

                    let expr: string;

                    if (f.decodeModel && f.isArray) {
                        expr = `[${decodeName(f.decodeModel)}(x) for x in raw.get(${key}) or []]`;
                    } else if (f.decodeModel) {
                        expr = `None if raw.get(${key}) is None else ${decodeName(f.decodeModel)}(raw.get(${key}))`;
                    } else {
                        expr = `raw.get(${key})`;
                    }

                    return `        ${JSON.stringify(f.name)}: ${expr},`;
                });

                return `def ${decodeName(d.model)}(raw: Any) -> ${d.model}:
    return {
${lines.join("\n")}
    }`;
            })
            .join("\n\n\n");

        return `${BANNER}from __future__ import annotations

from typing import Any

from .types import ${names.join(", ")}


${body}
`;
    },

    renderModule(mod: IrModule): string {
        const hasCall = mod.ops.some((op) => !op.zip);
        const hasZip = mod.ops.some((op) => op.zip);
        const runtimeImports = hasCall ? "Call, MethodCall, Module" : "Module";

        const hasEmbed = mod.ops.some((op) => op.params.some((p) => p.embed !== undefined));
        const imports = [];

        if (hasEmbed) {
            imports.push(`import json\n`);
        }

        imports.push(`from ...runtime import ${runtimeImports}`);

        if (hasZip) {
            imports.push(`from ...runtime.join import join_by`);
        }

        imports.push(`from ..types import ${[...mod.responses].sort().join(", ")}`);

        if (mod.enums.length > 0) {
            imports.push(`from ..enums import ${[...mod.enums].sort().join(", ")}`);
        }

        if (mod.decoderModels.length > 0) {
            const decoders = mod.decoderModels.map(decodeName).sort();
            imports.push(`from ..decoders import ${decoders.join(", ")}`);
        }

        const methods = mod.ops
            .map((op) => (op.zip ? zipMethod(mod, op) : callMethod(mod, op)))
            .join("\n\n");

        return `${BANNER}from __future__ import annotations

${imports.join("\n")}


class ${className(mod)}(Module):
${methods}
`;
    },

    renderClient(ir: IrProgram): string {
        const imports = ir.modules
            .map((m) => `from .modules.${m.name} import ${className(m)}`)
            .join("\n");
        const init = ir.modules
            .map((m) => `        self._${m.name} = ${className(m)}(self)`)
            .join("\n");
        const getters = ir.modules
            .map(
                (m) =>
                    `    @property\n    def ${m.name}(self) -> ${className(m)}:\n        return self._${m.name}`,
            )
            .join("\n\n");

        return `${BANNER}from __future__ import annotations

from ..runtime import BaseClient
${imports}


class Client(BaseClient):
    def __init__(self, auth: str | None = None) -> None:
        super().__init__(auth)

${init}

${getters}
`;
    },

    renderIndex(ir: IrProgram): string {
        const lines = ["from .client import Client", "from .enums import *  # noqa: F401,F403"];

        if (ir.hasDecoders) {
            lines.push("from .decoders import *  # noqa: F401,F403");
        }

        lines.push("from .types import *  # noqa: F401,F403");

        for (const m of ir.modules) {
            lines.push(`from .modules.${m.name} import ${className(m)}`);
        }

        return `${BANNER}${lines.join("\n")}\n`;
    },

    extraFiles(): GenFile[] {
        return [{ path: "modules/__init__.py", content: "" }];
    },
};
