import { compile as jsonToTs } from "json-schema-to-typescript";
import { join } from "node:path";
import type { Backend } from "../emit";
import type { IrModule, IrProgram, IrTransform, IrTransformPrimitive, IrType, IrZipField } from "../ir";

const ROOT = join(import.meta.dir, "../../../..");
const OUT = join(ROOT, "sdks/typescript/src/generated");
const SCHEMA = join(ROOT, "packages/pecans-spec/dist/@typespec/json-schema/pecans.json");
const BANNER = "/* Generated by pecans-spec. Do not edit. */\n";

function tsType(type: IrType): string {
    switch (type.kind) {
        case "int":
        case "float":
            return "number";

        case "bool":
            return "boolean";

        case "string":
            return "string";

        case "enum":
        case "model":
            return type.name;

        case "array":
            return `${tsType(type.element)}[]`;

        case "nullable":
            return `${tsType(type.inner)} | null`;

        default:
            return "any";
    }
}

function className(mod: IrModule): string {
    return `${mod.interfaceName}Module`;
}

function decodeName(model: string): string {
    return `decode${model}`;
}

function encodeName(model: string): string {
    return `encode${model}`;
}

/** Args literal for a transform primitive (the bitfield components / tuple fields). */
function transformArgs(p: IrTransformPrimitive): string {
    return p.kind === "bitfield" ? JSON.stringify(p.components) : JSON.stringify(p.fields);
}

/** Wire value -> struct, using the transform's decode primitive. */
function unpackExpr(t: IrTransform, value: string): string {
    const p = t.decode;
    const fn = p.kind === "bitfield" ? "bitfieldUnpack" : "tupleUnpack";
    return `${fn}(${value}, ${transformArgs(p)})`;
}

/** Struct -> wire value, using the transform's encode primitive. */
function packExpr(t: IrTransform, value: string): string {
    const p = t.encode;
    const fn = p.kind === "bitfield" ? "bitfieldPack" : "tuplePack";
    return `${fn}(${value}, ${transformArgs(p)})`;
}

/** Runtime transform helpers referenced anywhere in the generated converters. */
function transformHelpers(ir: IrProgram, encode: boolean): string[] {
    const used = new Set<string>();
    const fields = encode
        ? ir.encoders.flatMap((e) => e.fields)
        : ir.decoders.flatMap((d) => d.fields);

    for (const f of fields) {
        if (!f.transform) {
            continue;
        }

        const p = encode ? f.transform.encode : f.transform.decode;

        if (p.kind === "bitfield") {
            used.add(encode ? "bitfieldPack" : "bitfieldUnpack");
        } else {
            used.add(encode ? "tuplePack" : "tupleUnpack");
        }
    }

    return [...used].sort();
}

function zipSource(field: IrZipField): string {
    if (field.from === "result") {
        return `r.${field.field}`;
    }

    if (field.from === "input") {
        return `input.${field.field}`;
    }

    return "input";
}

/** Render a JSDoc block (indented one level) for a method, or "" if undocumented. */
function docBlock(op: IrModule["ops"][number]): string {
    const lines: string[] = [];

    if (op.doc) {
        lines.push(...op.doc.split("\n"));
    }

    const tags: string[] = [];

    for (const p of op.params) {
        if (p.doc) {
            tags.push(`@param ${p.name} - ${p.doc.replace(/\s*\n\s*/g, " ")}`);
        }
    }

    if (op.returnsDoc) {
        tags.push(`@returns ${op.returnsDoc.replace(/\s*\n\s*/g, " ")}`);
    }

    if (lines.length > 0 && tags.length > 0) {
        lines.push("");
    }

    lines.push(...tags);

    if (lines.length === 0) {
        return "";
    }

    const body = lines.map((l) => `     * ${l}`.trimEnd()).join("\n");
    return `    /**\n${body}\n     */\n`;
}

function signature(op: IrModule["ops"][number]): string {
    return op.params
        .map((p) => {
            if (p.hasDefault) {
                return `${p.name}: ${tsType(p.type)} = ${JSON.stringify(p.default)}`;
            }

            if (p.optional) {
                return `${p.name}?: ${tsType(p.type)}`;
            }

            return `${p.name}: ${tsType(p.type)}`;
        })
        .join(", ");
}

function payloadLiteral(op: IrModule["ops"][number]): string {
    const entries: string[] = [];

    // denormalize
    const encoded = (p: (typeof op.params)[number]): string => {
        if (p.encodeModel) {
            return p.encodeArray
                ? `(${p.name} ?? []).map(${encodeName(p.encodeModel)})`
                : `${p.name} == null ? ${p.name} : ${encodeName(p.encodeModel)}(${p.name})`;
        }

        if (p.transform) {
            return `${p.name} == null ? ${p.name} : ${packExpr(p.transform, p.name)}`;
        }

        return p.name;
    };

    for (const p of op.params) {
        if (p.embed !== undefined) {
            entries.push(
                `                ${JSON.stringify(p.embed)}: JSON.stringify(${encoded(p)}),`,
            );
            continue;
        }

        let value: string;

        if (p.joinSep !== undefined) {
            value = `${p.name}.join(${JSON.stringify(p.joinSep)})`;
        } else if (p.stringify) {
            value = p.type.kind === "bool" ? `(${p.name} ? "1" : "0")` : `String(${p.name})`;
        } else {
            value = encoded(p);
        }

        entries.push(`                ${JSON.stringify(p.wireName)}: ${value},`);

        for (const alt of p.also) {
            entries.push(`                ${JSON.stringify(alt)}: ${value},`);
        }
    }

    for (const [key, value] of Object.entries(op.constants)) {
        entries.push(`                ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
    }

    if (entries.length === 0) {
        return "{}";
    }

    return `{\n${entries.join("\n")}\n            }`;
}

function zipMethod(op: IrModule["ops"][number]): string {
    const z = op.zip!;
    const combine = z.fields.map((f) => `${f.name}: ${zipSource(f)}`).join(", ");

    return `${docBlock(op)}    public async ${op.method}(${signature(op)}): Promise<${z.element}[]> {
        const res = await this.${z.callMethod}(${z.input}.map((x) => x.${z.project}));

        return joinBy(
            ${z.input},
            res.${z.results} ?? [],
            (input) => input.${z.key},
            (r) => r.${z.key},
            (r, input) => ({ ${combine} }),
        );
    }`;
}

function callMethod(op: IrModule["ops"][number]): string {
    const decode = op.decodeModel ? `, ${decodeName(op.decodeModel)}` : "";

    return `${docBlock(op)}    public ${op.method}(${signature(op)}): Call<${op.response}> {
        return new Call<${op.response}>(this.client, {
            fn: ${JSON.stringify(op.fn)},
            payload: ${payloadLiteral(op)},
        }${decode});
    }`;
}

export const typescript: Backend = {
    outDir: OUT,
    ext: "ts",
    indexFile: "index.ts",

    async renderTypes(ir: IrProgram): Promise<string> {
        const exclude = new Set<string>(ir.modules.flatMap((m) => m.enums));

        const normalize = (node: unknown): unknown => {
            if (Array.isArray(node)) {
                return node.map(normalize);
            }

            if (node && typeof node === "object") {
                const out: Record<string, unknown> = {};

                for (const [key, value] of Object.entries(node)) {
                    if (key === "$id" || key === "$schema") {
                        continue;
                    }

                    if (key === "$ref" && typeof value === "string" && value.endsWith(".json")) {
                        out.$ref = `#/$defs/${value.slice(0, -".json".length)}`;
                        continue;
                    }

                    out[key] = normalize(value);
                }

                return out;
            }

            return node;
        };

        const bundle = normalize(await Bun.file(SCHEMA).json()) as {
            $defs: Record<string, unknown>;
        };

        for (const name of exclude) {
            delete bundle.$defs[name];
        }

        const root = {
            title: "PecansSchemaRoot",
            type: "object",
            additionalProperties: false,
            properties: Object.fromEntries(
                Object.keys(bundle.$defs).map((n) => [n, { $ref: `#/$defs/${n}` }]),
            ),
            $defs: bundle.$defs,
        };

        let ts = await jsonToTs(root as never, "PecansSchemaRoot", {
            bannerComment: BANNER,
            additionalProperties: false,
            declareExternallyReferenced: true,
        });

        ts = ts.replace(/export interface PecansSchemaRoot \{[\s\S]*?\n\}\n?/, "");
        return ts;
    },

    renderEnums(ir: IrProgram): string {
        const used = new Set<string>(ir.modules.flatMap((m) => m.enums));
        const blocks = ir.enums
            .filter((en) => used.has(en.name))
            .map((en) => {
                const members = en.members
                    .map((m) => `    ${m.name} = ${JSON.stringify(m.value)},`)
                    .join("\n");

                return `export enum ${en.name} {\n${members}\n}`;
            });

        return `${BANNER}${blocks.join("\n\n")}\n`;
    },

    renderDecoders(ir: IrProgram): string {
        const names = [...new Set(ir.decoders.map((d) => d.model))].sort();
        const body = ir.decoders
            .slice()
            .sort((a, b) => a.model.localeCompare(b.model))
            .map((d) => {
                const lines = d.fields.map((f) => {
                    const key = JSON.stringify(f.wireName);

                    let expr: string;

                    if (f.transform && f.isArray) {
                        expr = `(raw[${key}] ?? []).map((x: any) => ${unpackExpr(f.transform, "x")})`;
                    } else if (f.transform) {
                        expr = `raw[${key}] == null ? raw[${key}] : ${unpackExpr(f.transform, `raw[${key}]`)}`;
                    } else if (f.decodeModel && f.isArray) {
                        expr = `(raw[${key}] ?? []).map(${decodeName(f.decodeModel)})`;
                    } else if (f.decodeModel) {
                        expr = `raw[${key}] == null ? raw[${key}] : ${decodeName(f.decodeModel)}(raw[${key}])`;
                    } else {
                        expr = `raw[${key}]`;
                    }

                    return `        ${f.name}: ${expr},`;
                });

                return `export function ${decodeName(d.model)}(raw: any): ${d.model} {
    return {
${lines.join("\n")}
    };
}`;
            })
            .join("\n\n");

        const helpers = transformHelpers(ir, false);
        const helperImport = helpers.length
            ? `import { ${helpers.join(", ")} } from "../runtime/transform";\n`
            : "";

        return `${BANNER}import { ${names.join(", ")} } from "./types";\n${helperImport}\n${body}\n`;
    },

    renderEncoders(ir: IrProgram): string {
        const names = [...new Set(ir.encoders.map((e) => e.model))].sort();
        const body = ir.encoders
            .slice()
            .sort((a, b) => a.model.localeCompare(b.model))
            .map((e) => {
                const lines = e.fields.map((f) => {
                    const key = JSON.stringify(f.wireName);
                    const src = `value.${f.name}`;

                    let expr: string;

                    if (f.transform && f.isArray) {
                        expr = `(${src} ?? []).map((x) => ${packExpr(f.transform, "x")})`;
                    } else if (f.transform) {
                        expr = `${src} == null ? ${src} : ${packExpr(f.transform, src)}`;
                    } else if (f.encodeModel && f.isArray) {
                        expr = `(${src} ?? []).map(${encodeName(f.encodeModel)})`;
                    } else if (f.encodeModel) {
                        expr = `${src} == null ? ${src} : ${encodeName(f.encodeModel)}(${src})`;
                    } else {
                        expr = src;
                    }

                    return `        ${key}: ${expr},`;
                });

                return `export function ${encodeName(e.model)}(value: ${e.model}): any {
    return {
${lines.join("\n")}
    };
}`;
            })
            .join("\n\n");

        const helpers = transformHelpers(ir, true);
        const helperImport = helpers.length
            ? `import { ${helpers.join(", ")} } from "../runtime/transform";\n`
            : "";

        return `${BANNER}import { ${names.join(", ")} } from "./types";\n${helperImport}\n${body}\n`;
    },

    renderModule(mod: IrModule): string {
        const hasCall = mod.ops.some((op) => !op.zip);
        const hasZip = mod.ops.some((op) => op.zip);
        const runtimeImports = hasCall ? "Call, Module" : "Module";

        const imports = [`import { ${runtimeImports} } from "../../runtime";`];

        if (hasZip) {
            imports.push(`import { joinBy } from "../../runtime/join";`);
        }

        imports.push(`import { ${[...mod.responses].sort().join(", ")} } from "../types";`);

        if (mod.enums.length > 0) {
            imports.push(`import { ${[...mod.enums].sort().join(", ")} } from "../enums";`);
        }

        if (mod.decoderModels.length > 0) {
            const decoders = mod.decoderModels.map(decodeName).sort();
            imports.push(`import { ${decoders.join(", ")} } from "../decoders";`);
        }

        if (mod.encoderModels.length > 0) {
            const encoders = mod.encoderModels.map(encodeName).sort();
            imports.push(`import { ${encoders.join(", ")} } from "../encoders";`);
        }

        const methods = mod.ops.map((op) => (op.zip ? zipMethod(op) : callMethod(op))).join("\n\n");

        return `${BANNER}${imports.join("\n")}

export class ${className(mod)} extends Module {
${methods}
}
`;
    },

    renderClient(ir: IrProgram): string {
        const imports = ir.modules
            .map((m) => `import { ${className(m)} } from "./modules/${m.name}";`)
            .join("\n");
        const fields = ir.modules.map((m) => `    #${m.name}: ${className(m)};`).join("\n");
        const getters = ir.modules
            .map(
                (m) =>
                    `    public get ${m.name}(): ${className(m)} {\n        return this.#${m.name};\n    }`,
            )
            .join("\n\n");
        const init = ir.modules
            .map((m) => `        this.#${m.name} = new ${className(m)}(this);`)
            .join("\n");

        return `${BANNER}import { BaseClient } from "../runtime";
${imports}

export class Client extends BaseClient {
${fields}

    public constructor(auth?: string) {
        super(auth);
${init}
    }

${getters}
}
`;
    },

    renderIndex(ir: IrProgram): string {
        return `${BANNER}export * from "./types";
export * from "./enums";
${ir.hasDecoders ? `export * from "./decoders";\n` : ""}${ir.hasEncoders ? `export * from "./encoders";\n` : ""}export * from "./client";
${ir.modules.map((m) => `export * from "./modules/${m.name}";`).join("\n")}
`;
    },
};
